const express = require("express");
const router = express.Router();

var userController = require("../app/api/controllers/userController");
var claimController = require("../app/api/controllers/claimController");
var contactController = require("../app/api/controllers/contactController");
var lifeInsuranceController = require("../app/api/controllers/lifeInsuranceController");
var healthInsuranceController = require("../app/api/controllers/healthInsuranceController");
const companyController = require("../app/api/controllers/companyController");
router.get('/allUsers', userController.getAll);
router.get('/claim', claimController.getAll);
router.get('/contact', contactController.getAll);
router.get('/life', lifeInsuranceController.getAll);
router.get('/lifeInsuranceUsers', userController.lifeInsurance);
router.get('/investmentUsers', userController.investmentUsers);
router.get('/homeInsurUsers', userController.homeInsurUsers);
router.get('/healthInsurUsers', userController.healthInsurUsers);
router.get('/countAll', userController.countAll);
router.get('/search/:uname', userController.search);
router.get('/health', healthInsuranceController.get);
router.delete('/delete/:userId', userController.delete);
router.get('/company', companyController.getAll);
router.get('/allCompanies', companyController.countAll);
router.delete('/delCompany/:cId', companyController.delete);
router.get('/editUser/:id', userController.edit);
router.put('/updateUser/:userId', userController.updateById);
router.get('/tClaimRequests',claimController.countAll);
router.get('/janUsers', userController.janUsers);
router.get('/febUsers', userController.febUsers);
router.get('/marchUsers', userController.marchUsers);
router.get('/aprilUsers', userController.aprilUsers);
router.get('/mayUsers', userController.mayUsers);
router.get('/juneUsers', userController.juneUsers);
router.get('/julyUsers', userController.julyUsers);
router.get('/augUsers', userController.augUsers);
router.get('/sepUsers', userController.sepUsers);
router.get('/octUsers', userController.octUsers);
router.get('/novUsers', userController.novUsers);
router.get('/decUsers', userController.decUsers);
router.get('/tMessages', contactController.total);

module.exports = router;
