const express = require('express');
const router = express.Router();
const usrController = require("../app/api/controllers/userController");
const claimController = require('../app/api/controllers/claimController');
const lifeInsuranceController = require("../app/api/controllers/lifeInsuranceController");
const healthInsuranceController = require("../app/api/controllers/healthInsuranceController");
const contactController = require('../app/api/controllers/contactController');
const loginController = require("../app/api/controllers/userLoginController");
const investplanController = require("../app/api/controllers/investmentController");
router.post('/addNew',usrController.create);
router.post('/sendMessage', contactController.create);
router.post('/claimRequest', claimController.create);
router.post('/life', lifeInsuranceController.create);
router.get('/lifeRGet', lifeInsuranceController.getAll);
router.post('/health', healthInsuranceController.create);
router.get('/healthRGet', healthInsuranceController.get);
router.post('/investPlan', investplanController.create);
router.get('/investRGet', investplanController.getAll);
router.post('/login', loginController.login);
console.log("Router is Called");
module.exports = router;